[DRAFT] Public Release for Fall24 meta-release
camaraproject/CarrierBillingCheckOut pull request #178
Opened 2024-08-26 15:57 UTC by PedroDiez

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* documentation
* subproject management

#### What this PR does / why we need it:

PR to generate Public Release of Carrier Billing Checkout Family APIs

#### Which issue(s) this PR fixes:

Fixex #155 
Fixes #168
Fixes #173
Fixes #175 

#### Special notes for reviewers:

Changes driven in API Spec YAMLs:
- Apply File Name conventions (kebab-case)
- Adjustment of version and servers values
- Adjustment externalDocs link
- Adjustment sink Description
- Fix missing required request Body in `confirmPayment` operation
- Fix 401 Error with Commonalities and also align the model of Errors with Commonalities "CAMARA_common.yaml" naming. - - Remove 400 PhoneNumber Required as Covered by 422 Exception

**Pending**:
* API Readiness Checklist
* ChangeLog
* README.md

#### Changelog input

```
Public Release of Carrier Billing Family APIs for MetaRelease Fall24

```

#### Additional documentation 

N/A

2024-08-26 17:20 UTC, bigludo7 submitted a review, later dismissed
LGTM - Thanks @PedroDiez 
Up to @hdamker and the release Management team ;)

2024-08-28 19:22 UTC, hdamker commented
@PedroDiez If you want to have the meeting soon within main, you may want to do it in an own PR. Could take some days before the release PR gets approved by the RM team.

2024-09-03 11:11 UTC, jlurien requested changes
- API Readiness checklists should be updated to r1.2 versions (without -rc suffixes), and resolve any pending tbd

2024-09-03 16:36 UTC, PedroDiez commented
> @PedroDiez If you want to have the meeting soon within main, you may want to do it in an own PR. Could take some days before the release PR gets approved by the RM team.

Thanks Herbert, I will comment tomorrow in the WG meeting. I think we can wait because relevant people is already aware of new schedule

2024-09-04 07:47 UTC, jlurien commented on documentation/API_documentation/carrier-billing-refund-API-Readiness-Checklist.md
> +|  6 | User stories                                 |   O   |         O         |    O    |    M   |  N   | [link](/documentation/API_documentation/Carrier Billing Refund User Story.md) |
```suggestion
|  6 | User stories                                 |   O   |         O         |    O    |    M   |  Y   | [link](/documentation/API_documentation/Carrier Billing Refund User Story.md) |
```

2024-09-04 07:52 UTC, jlurien reviewed
Some projects are naming User stories with the same format than API-Readiness-Checklist, that is api-name-User-Story.md, but it is not made a requirement

2024-09-04 09:46 UTC, PedroDiez commented
> Some projects are naming User stories with the same format than API-Readiness-Checklist, that is api-name-User-Story.md, but it is not made a requirement

Thanks @jlurien I am applying it, It is fine to align

2024-09-04 10:07 UTC, jlurien approved these changes
Approved on behalf of Release Management

2024-09-05 15:28 UTC, PedroDiez commented
After TSC meeting, it can be merged:

SC Approval of M4 (all release PRs of Sub Project reviewed by Release Management)
- We can merge PR when review completed
- M4 Release tracker date:  date when the merged is done by the project

2024-09-05 15:28 UTC, merged